# Generated by Django 5.0.4 on 2024-07-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='wesbite',
            new_name='website',
        ),
    ]
